### ISSUE TITLE
automatic releases and luarocks/rocks.nvim support?

### ISSUE THREAD

**Issue by mrcjkb** [lawrence-laz/neotest-zig#28]
Hey :wave:

[rocks.nvim](https://github.com/nvim-neorocks/rocks.nvim) has the ability to install luarocks packages and automatically install dependencies, including tree-sitter parsers.

I was wondering: Would you be open to automating releases and publishing this plugin to luarocks.org?
See also [our wiki page on plugin support](https://github.com/nvim-neorocks/rocks.nvim/wiki/Plugin-support).

I'd be more than happy to help if you have any questions or issues.

**Comment by lawrence-laz** [comment]
Hi, 

I am not against it, but I don't use luarocks myself, so I am unlikely to find the time to set this up and maintain it.

If some user of both `neotest-zig` and `rocks.nvim` were to take up the ownership and maintenance of this process, then a PR would be welcome. :)

**Comment by mrcjkb** [comment]
I'm a rocks.nvim maintainer and also maintain neotest-haskell.
So I could open a PR if you like. I'd recommend you add the luarocks API key yourself though. I don't think it's a good idea to give strangers access to repo secrets :).
Another option would be just to add the release-please workflow here and to move luarocks publishing to [the NURR](https://github.com/nvim-neorocks/nurr).

**Comment by lawrence-laz** [comment]
Is the release-please workflow needed only for an automated git tag and/or github release? Does the NURR not work with manual releases?

**Comment by mrcjkb** [comment]
NURR searches for SemVer git tags. It doesn't matter if they were created automatically or not.

**Comment by lawrence-laz** [comment]
Makes sense. I've been needlessly prefixing tags with `v`, but otherwise they follow semver.
So I'll just drop the prefix and all should be good, right?

**Comment by mrcjkb** [comment]
The prefix is ignored by the luarocks workflow, so you can keep it if you want :)
If I add it to the NURR, there's nothing for you to do here and you can close this issue.
