### ISSUE TITLE
docs: Demo video is not playing in Firefox or in Quick-time when downloaded

### ISSUE THREAD

**Issue by asfaltboy** [lawrence-laz/neotest-zig#7]
**Describe the bug**

The video in the README (
https://github.com/lawrence-laz/neotest-zig/assets/8823448/2e959ca5-db2a-4eee-a422-48c11e853595) is not playable.

## **Steps To Reproduce**
1. Open firefox and navigate to the README, or download the file

## **Current behavior**

The video does not play unless I am using Chrome.

## **Expected behavior**

The video should play in all browsers, or when downloaded.

## **Screenshots**

![Screenshot 2023-12-10 at 18 51 45](https://github.com/lawrence-laz/neotest-zig/assets/321520/6c7ef01a-4c34-49bd-8373-fa3a4af03ff3)

## **Additional context**

We may want to look at another format.

Note: this is a docs-only issue.

**Comment by lawrence-laz** [comment]
Huh, that's odd. Re-encoded using `ffmpeg -i old.mp4 -vcodec libx264 -acodec aac new.mp4` and now it seems to be runnable.

Let me know if it works for you

**Comment by asfaltboy** [comment]
Looks great thank you @lawrence-laz 🙇
